### ISSUE TITLE
Getting CSS property always returns empty string

### ISSUE THREAD

**Issue by barancev** [jgraham/wires#16]
Log sample:
[bdd164c0-2322-41a3-9625-310d1236d73d, getElementValueOfCssProperty {id=fe665d82-651c-40ac-8e68-feea9fe00f6d, propertyName=opacity}]
1441551380774	Marionette	DEBUG	conn0 -> ({"name":"getElementValueOfCssProperty","parameters":{"id":"fe665d82-651c-40ac-8e68-feea9fe00f6d","name":"opacity"},"sessionId":"bdd164c0-2322-41a3-9625-310d1236d73d","to":"0"})
1441551380791	Marionette	DEBUG	conn0 client <- ({"from":"0","value":"","status":"success","sessionId":"bdd164c0-2322-41a3-9625-310d1236d73d"})
ERROR:webdriver::server: Returning status Ok
ERROR:webdriver::server: Returning body {"value":""}

**Comment by jgraham** [comment]
Oops.

Should be fixed in 68c483a934112a3342167dd1e82707f8445da55a Note that the following commit changes the protocol to match latest nightly Firefox, so it won't work if you are using something older.
