### ISSUE TITLE
It is not possible to call a function defined on the page

### ISSUE THREAD

**Issue by barancev** [jgraham/wires#18]
Let there be a page with displayMessage function defined:

INFO: Executing: executeScript [b55293e0-7e98-4cd8-9a71-19f219543449, executeScript {script=displayMessage('I like cheese');, args=[]}]
1441555505357	Marionette	DEBUG	conn0 -> ({"name":"executeScript","parameters":{"args":[],"newSandbox":false,"script":"displayMessage('I like cheese');","scriptTimeout":null,"specialPowers":false},"sessionId":"b55293e0-7e98-4cd8-9a71-19f219543449","to":"0"})
1441555505359	Marionette	DEBUG	conn0 client <- ({"from":"0","status":"javascript error","sessionId":"b55293e0-7e98-4cd8-9a71-19f219543449","error":{"message":"ReferenceError: displayMessage is not defined","stacktrace":"\ninline javascript, line 0\nsrc: \"let __marionetteFunc = function(){displayMessage('I like cheese');};__marionetteFunc.apply(null, __marionetteParams);\"","status":"javascript error"}})
ERROR:webdriver::server: Returning status InternalServerError
ERROR:webdriver::server: Returning body {"message":"Marionette Error: ReferenceError: displayMessage is not defined","status":"javascript error"}

**Comment by vladikoff** [comment]
dup of https://github.com/jgraham/wires/issues/15

**Comment by jgraham** [comment]
Actually this is a dupe. It's being worked on upstream.

**Comment by barancev** [comment]
Is this really a bug in marionette itself? I tested with today's Nightly and got the same error.

**Comment by jgraham** [comment]
Yes. Marionette runs all the js in a sandbox that doesn't have the content window as the global scope object. I believe you can work around the issue by running `window.displayMessage`, but the real fix will be upstream.

**Comment by titusfortner** [comment]
I'm trying to provide references for each Marionette test that is failing in the Ruby Selenium test suite. Is there a bug report upstream that deals with this?  Thanks.

**Comment by tex** [comment]
Sorry to wake up a zombie, but I have the same problem with latest firefox, marionette python client.
Is there any way to execute javascript function defined in loaded page?

**Comment by andreastt** [comment]
@tex Please file a new issue.
