### ISSUE TITLE
Unexpected alert open error is not returned

### ISSUE THREAD

**Issue by barancev** [jgraham/wires#21]
According to the spec:

"When a user prompt appears, it is the task of the subsequent command to handle it. If the subsequent requested command is not one listed in this chapter, an unexpected alert open error will be returned."
http://www.w3.org/TR/webdriver/#user-prompts

This Selenium test is designed to check this requirement:

```
  public void testIncludesAlertTextInUnhandledAlertException() {
    driver.findElement(By.id("alert")).click();
    wait.until(alertIsPresent());
    try {
      driver.getTitle();
      fail("Expected UnhandledAlertException");
    } catch (UnhandledAlertException e) {
      assertEquals("cheese", e.getAlertText());
      assertThat(e.getMessage(), containsString("cheese"));
    }
  }
```

But it fails due to lack of exception, getTitle command returns the title instead of unexpected alert open error.

**Comment by jgraham** [comment]
Sounds like a marionette issue: @andreastt

**Comment by andreastt** [comment]
Confirmed.  Reported as [bug 1206126](https://bugzilla.mozilla.org/show_bug.cgi?id=1206126).
