### ISSUE TITLE
Unknown command switchToParentFrame

### ISSUE THREAD

**Issue by barancev** [jgraham/wires#22]
INFO: Executing: switchToParentFrame [25bcb99d-d896-4bf7-ad69-6c55b39f5b09, switchToParentFrame {}]
1442232825843	Marionette	DEBUG	conn0 -> {"name":"switchToParentFrame","parameters":{},"sessionId":"25bcb99d-d896-4bf7-ad69-6c55b39f5b09"}
1442232825844	Marionette	DEBUG	conn0 client <- {"error":"unknown command","message":"switchToParentFrame","stacktrace":null}

**Comment by jgraham** [comment]
@andreastt I think this should be added as a command in marionette.

**Comment by andreastt** [comment]
@jgraham @barancev Yes, this is missing from Marionette.

**Switch To Parent Frame** is a relatively recent addition to the specification.  Marionette allows you to switch to the parent frame in the same style that Selenium does, by passing an empty string to **Switch To Frame**.

**Comment by andreastt** [comment]
Filed [bug 1206122](https://bugzilla.mozilla.org/show_bug.cgi?id=1206122).

**Comment by jgraham** [comment]
Oh, if this is supported in marionette, it's relatively easy to make the proxy use the existing support for now.

**Comment by jgraham** [comment]
Oh, the existing marionette command only allows you to switch to the topmost frame, which isn't what's required, in general. So I indeed can't fix this until the marionette bug is fixed. Leaving this open for now since it will have to be fixed once the backend supports it.

**Comment by andreastt** [comment]
Right you are, sir.  I’ve updated the bug.

**Comment by jgraham** [comment]
This just landed in m-c so should be in nightly tomorrow or so.
