### ISSUE TITLE
implement POST /session/{session id}/moz/context to allow selenium to switch context

### ISSUE THREAD

**Issue by AutomatedTester** [jgraham/wires#23]
The loop team need to be able to set context to do some Chrome testing. 

This should probably be

POST /session/{session id}/moz/context which send over a body with 
```{
  "value":"chrome"
}```

or

```{
  "value":"content"
}```

If it is neither of those it should throw an [invalid argument](http://w3c.github.io/webdriver/webdriver-spec.html#dfn-invalid-argument). Happy to bikeshed on this if you think there is a better way.

**Comment by jgraham** [comment]
Also requires a GET. I can implement this without too much difficulty.

**Comment by jgraham** [comment]
I made an implementation, so closing this. You'll still want a selenium change to actually use this from tests though.
