### ISSUE TITLE
Support using wires with the selenium-webdriver node package

### ISSUE THREAD

**Issue by marco-c** [jgraham/wires#24]
https://www.npmjs.com/package/selenium-webdriver

It should hopefully work with or without the standalone server (https://www.npmjs.com/package/selenium-webdriver#the-standalone-selenium-server).

**Comment by jgraham** [comment]
@AutomatedTester

**Comment by AutomatedTester** [comment]
This is coming. @jleyba will be adding support for this as soon as he can.

**Comment by jleyba** [comment]
Just pushed preliminary support for marionette to selenium-webdriver:

https://github.com/SeleniumHQ/selenium/commit/185755af93571b3a1b0e98dd4fbdc6ca23e8e085

**Comment by andreastt** [comment]
@jleyba 👍🏼
