### ISSUE TITLE
Expected payload for adding cookie does not match spec

### ISSUE THREAD

**Issue by jimevans** [jgraham/wires#25]
When adding a cookie, sending a payload to `POST /session/:sessionid/cookie` of
```json
{ 
  "cookie":
  {
    "name": "cookieName",
    "value": "cookieValue"
  }
}
```
results in a response of
```json
{
  "error":"invalid argument",
  "message":"Missing 'name' parameter"
}
```

Apparently, wires is expecting the cookie to not be wrapped in an outer object. This does not match the spec, which in step 3 of [the algorithm for the addCookie command](https://w3c.github.io/webdriver/webdriver-spec.html#add-cookie) states "Let _cookie_ be the result of getting a property named 'cookie' from the _parameters_ argument."

**Comment by jgraham** [comment]
Fixed in webdriver-rust 110625b02
