### ISSUE TITLE
local path overrides and unreleased versions

### ISSUE THREAD

**Issue by killerswan** [jgraham/wires#37]
Naively checking out just `wires` and running `cargo build --no-default-features`, I was getting an error about an unresolved import:
```
src\marionette.rs:22:43: 22:56 error: unresolved import `webdriver::command::WebDriverCommand::GetPageSource`. There is no `GetPageSource` in `webdriver::command::WebDriverCommand` [E0432]
src\marionette.rs:22     GoBack, GoForward, Refresh, GetTitle, GetPageSource, GetWindowHandle,
                                                               ^~~~~~~~~~~~~
```

If I understand correctly, to compile the latest `wires` I actually need to use @AutomatedTester's branch adding GetPageSource (https://github.com/jgraham/webdriver-rust/pull/20) rather than the latest version 0.5.0 of [webdriver](https://crates.io/crates/webdriver/) on Cargo.

I was able to fix the build by adding a `.cargo\config` file [as described here](http://doc.crates.io/guide.html#overriding-dependencies) to point to my clone of the `webdriver-rust` repo along side `wires`:
```
paths = ["./webdriver-rust"]
```

That was no problem, but might be worth mentioning in the README.  :smiley_cat:

**Comment by AutomatedTester** [comment]
Thanks for the issue. There is a PR for this waiting for when James is back and then will be released. I will close this for now.

There are new executables available in releases that have getPageSource available if you wanted.

**Comment by jgraham** [comment]
`</away>`FWIW I think making wires releases without publishing the corresponding `webdriver-rust` is a mistake, especially now that cargo supports installing binaries itself. I see why it happened this time, but in the future let's try to avoid it.`<away>`

**Comment by killerswan** [comment]
Thanks, @AutomatedTester and @jgraham!
