### ISSUE TITLE
Failed to decode request body as json

### ISSUE THREAD

**Issue by vladikoff** [jgraham/wires#45]
### STR
Get Wires, I used `master` with 4078409561fd4637fe16dd0c02acdb5c5bea5c25
Start wires with 
```
./wires -b /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin
```

```
git clone https://github.com/vladikoff/intern-quick-test.git -b fxa-signup
cd intern-quick-test 
npm i
npm test
```

### Expected

Fill out the form on accounts.firefox.com and submit

### Actual

```
➜  intern-quick-test git:(fxa-signup) ✗ npm test

> intern-quick-test@1.0.0 test /Users/vladikoff/dev/intern-quick-test
> intern-runner config=intern.js

Listening on 0.0.0.0:10232
Tunnel started
‣ Created session firefox on any platform (fde7e7a7-ccde-fd46-9c84-2c93c18991bc)
× firefox on any platform - suite1 - testTrue (1.524s)
UnknownError: [POST http://localhost:4444/session/fde7e7a7-ccde-fd46-9c84-2c93c18991bc/element/%5Bobject%20Object%5D/click] Failed to decode request body as json: 
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.testTrue [as test]  <testfunc1.js:15:12>
  at <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
```

Could be related to https://github.com/jgraham/wires/issues/10

**Comment by vladikoff** [comment]
My test code:

https://github.com/vladikoff/intern-quick-test/blob/fxa-signup/testfunc1.js

```
return this.remote
        .get(require.toUrl('https://accounts.firefox.com'))
        .setFindTimeout(100000)

        .findByCssSelector('form input.email')
          .click()
          .type('some@email.com')
        .end()

        .findByCssSelector('form input.password')
          .click()
          .type('password')
        .end()

        .findByCssSelector('button[type="submit"]')
          .click()
        .end();
```

**Comment by vladikoff** [comment]
Debugging this I see different behaviour from Selenium
## Selenium

### Get Element
![](http://v14d.com/i/56a7f64e9ee99.jpg)
### Click
![](http://v14d.com/i/56a7f66d9d1ae.jpg)

## Wires

### Get Element
![](http://v14d.com/i/56a7f772dd6f5.jpg)

### Click
![](http://v14d.com/i/56a7f77dd4d26.jpg)


@csnover any input?

**Comment by andreastt** [comment]
It looks like your code is requesting by POST a URL with the normalisation of `[object Object]` in it:

`UnknownError: [POST http://localhost:4444/session/fde7e7a7-ccde-fd46-9c84-2c93c18991bc/element/%5Bobject%20Object%5D/click]`

Here `%5Bobject%20Object%5D` is supposed to be a UUID of a web element.

**Comment by vladikoff** [comment]
> It looks like your code is requesting by POST a URL with the normalisation of [object Object] in it:
UnknownError: [POST http://localhost:4444/session/fde7e7a7-ccde-fd46-9c84-2c93c18991bc/element/%5Bobject%20Object%5D/click]
Here %5Bobject%20Object%5D is supposed to be a UUID of a web element.

Yeah that should be fixed easily. However the main compatibility difference is that Selenium returns `0` and Wires returns `{ element-6066...: '150.....'}`. I'm not sure where to look to understand which value should be parsed out the key or the value. I guess if you are saying "UUID" then it is the `value` and not the key.

**Comment by andreastt** [comment]
I’m not entirely sure I understand what you’re saying, but the [web element identifier](http://w3c.github.io/webdriver/webdriver-spec.html#dfn-web-element-identifier) is `element-6066-11e4-a52e-4f735466cecf`.  This replaces what in Selenium was known as the `ELEMENT` key.  The web element identifier is a hard-coded constant used to distinguish web element references in a dictionary returned from [executing script](http://w3c.github.io/webdriver/webdriver-spec.html#executing-script).

For the click, can you show me the exact request you’re making to wires?
