### ISSUE TITLE
There is no way to use addons

### ISSUE THREAD

**Issue by Athl33t** [jgraham/wires#50]
With Selenium FirefoxDriver we can specify a FirefoxProfile and add extensions.

>             FirefoxProfile firefoxProfile = new FirefoxProfile();
>             firefoxProfile.AddExtension(@"path to .xpi");
>             FirefoxDriver driver = new FirefoxDriver(firefoxProfile);

However, wires offers no such API. Is there a way to have wires load a users Firefox extensions?

**Comment by jgraham** [comment]
There is a partial fix for this on https://github.com/jgraham/wires/tree/profile

**Comment by vladikoff** [comment]
The Sync / FxA team is also interested in this and the profile feature, I will try out that branch and see how well it works for us. Thanks!

**Comment by Athl33t** [comment]
Thanks, this is a good start. For right now I just need a way to get marionette to start with a particular addon. Is there a way for me to hardcode this in wires for the time being?

**Comment by AutomatedTester** [comment]
this was landed in 3045c00a77b7ef7220ec9a6b318cae0756221a87
